//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace News
{
    using System;
    using System.Collections.Generic;
    
    public partial class LSBaiViet
    {
        public int ID { get; set; }
        public Nullable<int> ID_User { get; set; }
        public Nullable<int> ID_BaiViet { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string GhiChu { get; set; }
    
        public virtual BaiViet BaiViet { get; set; }
        public virtual User User { get; set; }
    }
}
