//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace News
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class NewsEntities2 : DbContext
    {
        public NewsEntities2()
            : base("name=NewsEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Anh> Anh { get; set; }
        public virtual DbSet<BaiViet> BaiViet { get; set; }
        public virtual DbSet<ChuyenMuc> ChuyenMuc { get; set; }
        public virtual DbSet<Comment> Comment { get; set; }
        public virtual DbSet<LoaiTK> LoaiTK { get; set; }
        public virtual DbSet<LoginReader> LoginReader { get; set; }
        public virtual DbSet<LSBaiViet> LSBaiViet { get; set; }
        public virtual DbSet<QuangCao> QuangCao { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<ThongKe> ThongKe { get; set; }
        public virtual DbSet<User> User { get; set; }
    
        public virtual ObjectResult<spThongKe_Edit_Result> spThongKe_Edit()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spThongKe_Edit_Result>("spThongKe_Edit");
        }
    }
}
