//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace News
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public int ID { get; set; }
        public int ID_User { get; set; }
        public Nullable<int> ID_ChuyenMuc { get; set; }
        public Nullable<int> ID_LoaiTK { get; set; }
    
        public virtual ChuyenMuc ChuyenMuc { get; set; }
        public virtual LoaiTK LoaiTK { get; set; }
        public virtual User User { get; set; }
    }
}
