//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace News
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_BaiViet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_BaiViet()
        {
            this.tb_Comment = new HashSet<tb_Comment>();
            this.tb_LSBaiViet = new HashSet<tb_LSBaiViet>();
        }
    
        public int ID_BaiViet { get; set; }
        public string TenBaiViet { get; set; }
        public Nullable<int> ID_User { get; set; }
        public Nullable<int> ID_ChuyenMuc { get; set; }
        public string AnhDaiDien { get; set; }
        public string TomTat { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> TGViet { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<double> LuotXem { get; set; }
    
        public virtual tb_ChuyenMuc tb_ChuyenMuc { get; set; }
        public virtual tb_User tb_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Comment> tb_Comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_LSBaiViet> tb_LSBaiViet { get; set; }
    }
}
