//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace News
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ChuyenMuc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_ChuyenMuc()
        {
            this.tb_BaiViet = new HashSet<tb_BaiViet>();
            this.tb_Role = new HashSet<tb_Role>();
        }
    
        public int ID_ChuyenMuc { get; set; }
        public string TenChuyenMuc { get; set; }
        public Nullable<int> ID_ChuyenMucCha { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_BaiViet> tb_BaiViet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Role> tb_Role { get; set; }
    }
}
