//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace News_Users
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anh
    {
        public int ID_Anh { get; set; }
        public Nullable<int> ID_BaiViet { get; set; }
        public string URL { get; set; }
        public Nullable<int> ViTri { get; set; }
        public string Tieude { get; set; }
    
        public virtual BaiViet BaiViet { get; set; }
    }
}
