//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace News_Users
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiViet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BaiViet()
        {
            this.Anh = new HashSet<Anh>();
            this.Comment = new HashSet<Comment>();
            this.LSBaiViet = new HashSet<LSBaiViet>();
        }
    
        public int ID_BaiViet { get; set; }
        public string TenBaiViet { get; set; }
        public Nullable<int> ID_User { get; set; }
        public Nullable<int> ID_ChuyenMuc { get; set; }
        public string AnhThumbnail { get; set; }
        public string TomTat { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<System.DateTime> TGViet { get; set; }
        public string NoiDung { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Anh> Anh { get; set; }
        public virtual ChuyenMuc ChuyenMuc { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LSBaiViet> LSBaiViet { get; set; }
    }
}
