//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace News_Users
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int ID_Comment { get; set; }
        public Nullable<int> ID_BaiViet { get; set; }
        public Nullable<int> ID_Reader { get; set; }
        public string Comment1 { get; set; }
    
        public virtual BaiViet BaiViet { get; set; }
        public virtual LoginReader LoginReader { get; set; }
    }
}
